### ISSUE TITLE
Not populated in HTML

### ISSUE THREAD

**Issue by kiavash-google** [google/pcbdl#2]
When the part is not populated, the generated HTML should mention "Do Not Populate!"

	--- a/pcbdl/html.py
	+++ b/pcbdl/html.py
	@@ -63,9 +63,13 @@ class HTMLPart(Plugin):
	 
					if part.__doc__:
							yield "<pre>%s</pre>" % textwrap.dedent(part.__doc__.rstrip())

					yield "<p>Value: %s</p>" % part.value
	-               yield "<p>Part Number: %s</p>" % part.part_number
	+
	+               if part.populated:
	+                       yield "<p>Part Number: %s</p>" % part.part_number
	+               else:
	+                       yield "<p>Do Not Populate!</p>"

**Comment by amstan** [comment]
Per in person conversation:
* Part number will remain regardless, just in case one wants to see what part number they have the option of populating and also to encourage people to put a real part number for potential things instead of "DNS".
* What I really want is the whole part in the html to maybe turn gray when "not part.populated".
